import yt_dlp
import os
import time

def download_audio(video_url, output_dir, logger):
    """
    Downloads audio from YouTube video using yt-dlp.
    Returns path to the downloaded audio file.
    """
    # Store the last log time (using list or dict to allow modification in nested functions)
    last_log_time = {"time": 0}

    def progress_hook(d):
        if d['status'] == 'downloading':
            current_time = time.time()
            # Check if it has been more than 10 seconds since the last log
            if current_time - last_log_time["time"] >= 10:
                percent = d.get('_percent_str', '0%')
                speed = d.get('_speed_str', 'N/A')
                eta = d.get('_eta_str', 'N/A')
                logger.info(f"Download progress: {percent} | Speed: {speed} | Estimated time remaining: {eta}")
                
                # Update last log time
                last_log_time["time"] = current_time
        
        elif d['status'] == 'finished':
            logger.info("Download completed, now processing with FFmpeg...")

    logger.info(f"Downloading audio from {video_url}...")
    
    ydl_opts = {
        'format': 'bestaudio/best',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'm4a',
        }],
        'outtmpl': os.path.join(output_dir, '%(id)s.%(ext)s'),
        'quiet': True,
        'no_warnings': True,
        'progress_hooks': [progress_hook],
    }
    
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    max_retries = 5
    for attempt in range(max_retries + 1):
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(video_url, download=True)
                filename = ydl.prepare_filename(info)
                # filenames with 'm4a' extension are generated by postprocessor
                base, _ = os.path.splitext(filename)
                final_path = base + ".m4a"
                
                logger.info(f"Downloaded: {final_path}")
                return final_path
        except Exception as e:
            error_msg = str(e)
            if "This live event will begin in a few moments." in error_msg:
                if attempt < max_retries:
                    logger.warning(f"Error downloading {video_url}: {error_msg}")
                    logger.info(f"Retrying in 15 seconds... (Attempt {attempt + 1} of {max_retries})")
                    time.sleep(15)
                else:
                    logger.warning(f"Error downloading {video_url}: {error_msg}")
                    return "LIVE_EVENT_UPCOMING"
            else:
                logger.critical(f"Error downloading {video_url}: {e}")
                return None
    return None
