import yt_dlp
import os

def download_audio(video_url, output_dir, logger):
    """
    Downloads audio from YouTube video using yt-dlp.
    Returns path to the downloaded audio file.
    """
    logger.info(f"Downloading audio from {video_url}...")
    
    ydl_opts = {
        'format': 'bestaudio/best',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'm4a',
        }],
        'outtmpl': os.path.join(output_dir, '%(id)s.%(ext)s'),
        'quiet': True,
        'no_warnings': True,
    }
    
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(video_url, download=True)
            filename = ydl.prepare_filename(info)
            # filenames with 'm4a' extension are generated by postprocessor
            base, _ = os.path.splitext(filename)
            final_path = base + ".m4a"
            
            logger.info(f"Downloaded: {final_path}")
            return final_path
    except Exception as e:
        logger.critical(f"Error downloading {video_url}: {e}")
        return None
